export interface CredentialEntry {
  profession: string;
  emoji: string;
  regulatoryBody: string;
  regulatoryBodyUrl: string;
  steps: string[];
  timeline: string;
  notes: string;
}

export const CREDENTIALS: CredentialEntry[] = [
  {
    profession: 'Registered Nurse',
    emoji: '🏥',
    regulatoryBody: 'CRNA Alberta (via NNAS)',
    regulatoryBodyUrl: 'https://nurses.ab.ca',
    steps: [
      'Submit application to NNAS (National Nursing Assessment Service) — nnas.ca',
      'Gather and submit all nursing education and work history documents',
      'NNAS completes assessment (3–6 months) and sends report to CRNA Alberta',
      'CRNA Alberta reviews and determines registration pathway',
      'Complete any required bridging courses or exams',
      'Apply for CRNA registration and obtain licence',
    ],
    timeline: '6–18 months total',
    notes: 'Start NNAS the day you arrive. The process is long — begin immediately.',
  },
  {
    profession: 'Engineer / Geoscientist',
    emoji: '⚙️',
    regulatoryBody: 'APEGA',
    regulatoryBodyUrl: 'https://www.apega.ca',
    steps: [
      'Submit application to APEGA with academic transcripts and experience records',
      'APEGA evaluates your credentials against Canadian engineering standards',
      'May require additional exams (Confirmatory, Technical) depending on your degree',
      'Work under supervision with a Permit to Practice while awaiting full registration',
      'Complete required Professional Practice Exam (PPE)',
      'Receive Professional Engineer (P.Eng.) or Professional Geoscientist (P.Geo.) designation',
    ],
    timeline: '1–3 years',
    notes: 'Apply before you arrive if possible. APEGA has a member support team for newcomers.',
  },
  {
    profession: 'Physician / Doctor',
    emoji: '⚕️',
    regulatoryBody: 'CPSA (via AMC)',
    regulatoryBodyUrl: 'https://cpsa.ca',
    steps: [
      'Have credentials assessed by AMC (Australian Medical Council) or ECFMG',
      'Pass MCCQE Part 1 (Medical Council of Canada Qualifying Exam)',
      'Complete a Canadian residency program (Postgraduate medical training)',
      'Pass MCCQE Part 2',
      'Apply to CPSA (College of Physicians and Surgeons of Alberta) for registration',
      'Obtain a practice permit',
    ],
    timeline: '2–7 years (residency dependent)',
    notes: 'Contact CPSA early for your specific pathway. Some jurisdictions have expedited routes for specialists.',
  },
  {
    profession: 'Accountant / CPA',
    emoji: '📊',
    regulatoryBody: 'CPA Alberta',
    regulatoryBodyUrl: 'https://www.cpaalberta.ca',
    steps: [
      'Submit a credential evaluation request to CPA Alberta',
      'CPA Alberta compares your qualifications to Canadian CPA standards',
      'Complete gap education (if required) through a CPA PEP program',
      'Pass the Common Final Examination (CFE) — if not exempt',
      'Complete 30 months of relevant work experience under a CPA mentor',
      'Receive Canadian CPA designation',
    ],
    timeline: '1–4 years (depends on home country CPA equivalency)',
    notes: 'If you hold a CPA equivalent from a country with a mutual recognition agreement (MRA), the process is significantly shorter.',
  },
  {
    profession: 'Electrician / Trades',
    emoji: '🔧',
    regulatoryBody: 'Alberta Apprenticeship and Industry Training (AIT)',
    regulatoryBodyUrl: 'https://tradesecrets.alberta.ca',
    steps: [
      'Contact Alberta AIT to have your foreign trade credentials assessed',
      'Submit your trade certificate, transcripts, and work experience records',
      'AIT determines if you qualify for Challenge Exams (write the exam without serving apprenticeship)',
      'Pass the Journeyman Certificate of Competency exam for your trade',
      'Apply for Alberta Journeyman Certificate',
    ],
    timeline: '3–12 months',
    notes: 'Many trades qualify for Challenge Exams. NorQuest College offers trades bridging programs.',
  },
  {
    profession: 'Teacher',
    emoji: '📚',
    regulatoryBody: 'Alberta Teachers Association (ATA)',
    regulatoryBodyUrl: 'https://www.teachers.ab.ca',
    steps: [
      'Apply to Alberta Education for Teacher Certification',
      'Submit degree transcripts, teaching certificate, and letter of standing from home country',
      'Alberta Education evaluates credentials (2–4 months)',
      'May require additional coursework in Alberta curriculum or child development',
      'Receive Interim or Permanent Alberta Teaching Certificate',
    ],
    timeline: '6–18 months',
    notes: 'Contact your local school board — some will hire on an Interim Certificate while your full certification is processed.',
  },
  {
    profession: 'Pharmacist',
    emoji: '💊',
    regulatoryBody: 'Alberta College of Pharmacy (ACP)',
    regulatoryBodyUrl: 'https://abpharmacy.ca',
    steps: [
      'Apply to the Pharmacy Examining Board of Canada (PEBC) for credential evaluation',
      'Pass PEBC Evaluating Exam (written)',
      'Complete an Structured Practical Training (SPT) placement in Alberta',
      'Pass PEBC Qualifying Exam (written + OSCE)',
      'Apply to ACP for registration',
    ],
    timeline: '1–3 years',
    notes: 'The PEBC evaluating exam can be written outside Canada — start before arriving if possible.',
  },
  {
    profession: 'Lawyer / Legal Professional',
    emoji: '⚖️',
    regulatoryBody: 'Law Society of Alberta',
    regulatoryBodyUrl: 'https://www.lawsociety.ab.ca',
    steps: [
      'Have credentials assessed by the Federation of Law Societies of Canada (NCA)',
      'Complete any required NCA exams (varies by country of training)',
      'Apply to a Canadian law school for the National Committee on Accreditation program if required',
      'Complete articling year under an Alberta lawyer',
      'Pass the Law Society bar admission course and exams',
      'Apply for membership in the Law Society of Alberta',
    ],
    timeline: '2–5 years',
    notes: 'Lawyers from Common Law countries may have an expedited NCA process.',
  },
];

export const LICENCE_EXCHANGE_COUNTRIES: { country: string; requiresTest: boolean; notes: string }[] = [
  { country: 'United States', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'United Kingdom', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Australia', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'South Korea', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Japan', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Germany', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'France', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Switzerland', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Austria', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Belgium', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Netherlands', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'New Zealand', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Singapore', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Hong Kong', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Taiwan', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Ukraine', requiresTest: false, notes: 'Direct exchange — no road test.' },
  { country: 'Philippines', requiresTest: true, notes: 'Written knowledge test required. No road test.' },
  { country: 'India', requiresTest: true, notes: 'Written knowledge test required. Road test required.' },
  { country: 'Sudan', requiresTest: true, notes: 'Written knowledge test and road test required.' },
  { country: 'Nigeria', requiresTest: true, notes: 'Written knowledge test and road test required.' },
  { country: 'Pakistan', requiresTest: true, notes: 'Written knowledge test and road test required.' },
  { country: 'Bangladesh', requiresTest: true, notes: 'Written knowledge test and road test required.' },
  { country: 'Eritrea', requiresTest: true, notes: 'Written knowledge test and road test required.' },
  { country: 'Ethiopia', requiresTest: true, notes: 'Written knowledge test and road test required.' },
  { country: 'Other', requiresTest: true, notes: 'Contact Alberta Registry to confirm your country\'s requirements.' },
];
