import type { Step } from '../types/Step';

export const STEPS_FALLBACK: Step[] = [
  {
    id: 'step_1_arrival',
    stepNumber: 1,
    title: 'Arrival essentials',
    timing: 'Day 1–3',
    offlineAvailable: true,
    whyItMatters: 'These tasks cannot wait — they unlock everything else.',
    actions: [
      { id: 'sin', text: 'Apply for SIN (Social Insurance Number) — online at sin-nas.canada.ca (5 business days) or same-day at any Service Canada office. Bring: passport + immigration document.' },
      { id: 'photocopy', text: 'Photocopy all documents ×10: passport, immigration document, IRCC confirmation letter. Store copies separately from originals.' },
      { id: 'settlement', text: 'Find nearest settlement agency: EMCN (11713 82 St NW, Edmonton), Catholic Social Services, or EISA — all free, no faith requirement.' },
      { id: 'sim', text: 'Get a Canadian SIM card — Koodo, Fido, and Lucky Mobile have affordable prepaid plans.' },
      { id: 'documents', text: 'Understand which documents to always carry vs. keep safe at home.' },
    ],
    documents: [
      { id: 'passport', name: 'Passport', whyNeeded: 'Primary ID for all government services', whereToGet: 'You already have this' },
      { id: 'permit', name: 'Work permit / PR card / IRCC letter', whyNeeded: 'Proof of immigration status', whereToGet: 'Provided by IRCC on approval' },
      { id: 'address', name: 'Proof of address', whyNeeded: 'Required for most registrations', whereToGet: 'Lease agreement or hotel confirmation' },
    ],
    resources: [
      { label: 'Apply for SIN — Service Canada', url: 'https://www.canada.ca/en/employment-social-development/services/sin.html' },
      { label: 'EMCN — Edmonton Mennonite Centre for Newcomers', url: 'https://emcn.ab.ca' },
    ],
    personaNotes: [
      { status: 'refugee', note: 'A settlement worker is assigned at arrival — this app supplements their support.' },
    ],
  },
  {
    id: 'step_2_ahcip',
    stepNumber: 2,
    title: 'Apply for AHCIP',
    timing: 'Week 1',
    offlineAvailable: true,
    whyItMatters: "Alberta's free public health insurance. No monthly premium. The 3-month waiting period clock starts the day you establish residency — apply immediately.",
    actions: [
      { id: 'eligibility', text: 'Check eligibility: permanent residents, and temporary residents with work/study permits valid 12+ months all qualify.' },
      { id: 'apply', text: 'Apply online at alberta.ca/ahcip OR in person at any Alberta Registry office.' },
      { id: 'documents', text: 'Required documents: valid immigration document + passport + proof of Alberta address (lease, utility bill, or bank statement).' },
      { id: 'refugee_note', text: 'IMPORTANT: The 3-month waiting period is WAIVED for Convention Refugees and Protected Persons — coverage starts immediately.' },
      { id: 'during_wait', text: 'During the wait: access Community Health Centres (sliding scale fees), U of A School of Dentistry (reduced rates), and Canadian Dental Care Plan (CDCP) if household income under $90,000.' },
      { id: 'missed', text: 'If you miss the 3-month window, your coverage start date is delayed to when your application is processed.' },
    ],
    documents: [
      { id: 'immigration', name: 'Immigration document', whyNeeded: 'Proves your status and permit validity', whereToGet: 'IRCC issued at border or by mail' },
      { id: 'passport', name: 'Passport', whyNeeded: 'Identity verification', whereToGet: 'You already have this' },
      { id: 'address', name: 'Proof of Alberta address', whyNeeded: 'Proves Alberta residency', whereToGet: 'Lease, utility bill, or bank statement' },
    ],
    resources: [
      { label: 'Apply for AHCIP — Alberta.ca', url: 'https://www.alberta.ca/ahcip-apply.aspx' },
      { label: 'Find an Alberta Registry office', url: 'https://www.alberta.ca/registry-agent-locations.aspx' },
    ],
    personaNotes: [
      { status: 'refugee', note: 'No waiting period for Convention Refugees and Protected Persons — coverage starts immediately on approval.' },
      { status: 'cuaet', note: 'CUAET qualifies as a work permit for AHCIP purposes. You have a 3-month waiting period.' },
    ],
  },
  {
    id: 'step_3_banking',
    stepNumber: 3,
    title: 'Banking & financial setup',
    timing: 'Week 2',
    offlineAvailable: true,
    whyItMatters: 'A Canadian bank account unlocks direct deposit for government benefits, rent payments, and building credit history.',
    actions: [
      { id: 'account', text: 'Open a newcomer account: RBC Newcomer Advantage, TD New to Canada, CIBC Smart Account for Newcomers, or Scotiabank StartRight — all offer 0 monthly fees for 12 months.' },
      { id: 'bring', text: 'Bring: passport + immigration document + proof of address. Most banks do not require SIN to open (but add it later).' },
      { id: 'credit', text: 'Apply for a secured credit card (requires a deposit = credit limit) — this starts your Canadian credit history. Credit history from home country does not transfer.' },
      { id: 'cra', text: 'Register for CRA (Canada Revenue Agency) My Account at canada.ca/my-cra-account — needed for tax filing and benefits.' },
      { id: 'remittance', text: 'Remittance: compare Wise (low fees), Remitly, and bank wire before sending money internationally.' },
    ],
    documents: [
      { id: 'passport', name: 'Passport', whyNeeded: 'Primary ID for bank account opening', whereToGet: 'You already have this' },
      { id: 'immigration', name: 'Immigration document', whyNeeded: 'Proof of status', whereToGet: 'IRCC issued' },
      { id: 'address', name: 'Proof of address', whyNeeded: 'Required to open account', whereToGet: 'Lease or utility bill' },
      { id: 'sin', name: 'SIN (add later)', whyNeeded: 'Needed for interest reporting and benefits', whereToGet: 'Service Canada — apply in Step 1' },
    ],
    resources: [
      { label: 'RBC Newcomer Advantage', url: 'https://www.rbc.com/newcomers' },
      { label: 'TD New to Canada', url: 'https://www.td.com/ca/en/personal-banking/newcomers' },
    ],
    personaNotes: [
      { status: 'refugee', note: 'RAP (Resettlement Assistance Program) may provide initial financial support — ask your settlement worker.' },
    ],
  },
  {
    id: 'step_4_housing',
    stepNumber: 4,
    title: 'Housing & tenant rights',
    timing: 'Week 2–3',
    offlineAvailable: true,
    whyItMatters: "Alberta's Residential Tenancies Act protects all tenants — most newcomers do not know their rights until they need them.",
    actions: [
      { id: 'clauses', text: 'Before signing: check for illegal clauses — landlords cannot charge more than 1 month rent as security deposit, cannot enter without 24h notice, cannot cut utilities.' },
      { id: 'rights', text: 'Know your rights: minimum notice for rent increase is 3 months, eviction requires proper cause and notice.' },
      { id: 'records', text: 'Keep records: document the state of the unit on move-in with photos. Date-stamp everything.' },
      { id: 'risk', text: 'If at risk of homelessness: contact City of Edmonton Housing Relocation Team, FCSS emergency supports, or dial 211 Alberta.' },
      { id: 'resources', text: "Rental resources: Edmonton's affordable housing waitlist, Civida housing, EMCN emergency housing referrals." },
      { id: 'dispute', text: 'Tenant dispute resolution: RTDRS (Residential Tenancy Dispute Resolution Service) — no lawyer needed, low cost.' },
    ],
    documents: [
      { id: 'lease', name: 'Signed lease', whyNeeded: 'Legal record of your tenancy terms', whereToGet: 'From your landlord — keep a copy' },
      { id: 'inspection', name: 'Move-in inspection checklist', whyNeeded: 'Protects your security deposit', whereToGet: 'Photograph all rooms on move-in day' },
    ],
    resources: [
      { label: 'RTDRS — Tenant Dispute Resolution', url: 'https://www.alberta.ca/residential-tenancy-dispute-resolution-service.aspx' },
      { label: '211 Alberta — Emergency support', url: 'https://ab.211.ca' },
    ],
    personaNotes: [
      { status: 'cuaet', note: 'RTDRS can help if you signed an unfair lease. File within 2 years of the incident.' },
      { status: 'refugee', note: 'EMCN has emergency housing referrals. Call 780-424-7709 if you need immediate shelter.' },
    ],
  },
  {
    id: 'step_5_employment',
    stepNumber: 5,
    title: 'Employment & credential recognition',
    timing: 'Month 1',
    offlineAvailable: false,
    whyItMatters: 'Credential recognition is the single largest barrier for internationally trained professionals in Alberta.',
    actions: [
      { id: 'regulatory', text: 'Identify your regulatory body: Nursing → NNAS then CRNA Alberta; Engineering → APEGA; Medicine → AMC then CPSA; Accounting → CPA Alberta; Trades → Alberta AIT.' },
      { id: 'rights', text: 'Know your workplace rights: minimum wage is $15.65/hr, WCB covers workplace injuries from day one, EI requires 420–700 insurable hours before claiming.' },
      { id: 'wagetheft', text: 'Wage theft: if an employer underpays, file a complaint with Alberta Employment Standards — free, no lawyer needed.' },
      { id: 'jobs', text: 'Job resources in Edmonton: ERIEC (employer-newcomer matching), Bredin Centre for Career Advancement, NorQuest trades pathways, Business Link (self-employment).' },
      { id: 'linkedin', text: 'LinkedIn profile: many Edmonton employers screen LinkedIn before interviews — settlement agencies can help build yours.' },
    ],
    documents: [
      { id: 'credentials', name: 'Credential documents (translated & notarised)', whyNeeded: 'Required by regulatory bodies', whereToGet: 'Get translated by a certified translator' },
      { id: 'transcripts', name: 'Foreign degree transcripts', whyNeeded: 'Educational credential assessment', whereToGet: 'From your university/college' },
      { id: 'licence', name: 'Professional licence from home country', whyNeeded: 'Confirms prior professional registration', whereToGet: 'From your home country regulatory body' },
    ],
    resources: [
      { label: 'ERIEC — Employer-newcomer matching', url: 'https://eriec.ca' },
      { label: 'APEGA — Engineers & Geoscientists', url: 'https://www.apega.ca' },
      { label: 'NNAS — Nursing credential assessment', url: 'https://www.nnas.ca' },
      { label: 'CPA Alberta', url: 'https://www.cpaalberta.ca' },
    ],
    personaNotes: [
      { status: 'work_permit', note: 'NNAS application takes 3–6 months — start immediately if you are a nurse.' },
      { status: 'cuaet', note: 'CPA Canada credential evaluation via CPA Alberta — contact them for the CUAET fast-track.' },
      { status: 'pr', note: 'As a PR you can access all publicly funded employment programs including LINC and bridge programs.' },
    ],
  },
  {
    id: 'step_6_language',
    stepNumber: 6,
    title: 'Language & community connection',
    timing: 'Month 2',
    offlineAvailable: true,
    whyItMatters: 'LINC (Language Instruction for Newcomers to Canada) is fully funded by IRCC for eligible residents. Community connection is a proven predictor of successful settlement.',
    actions: [
      { id: 'linc', text: "Register for LINC: EMCN is Alberta's largest LINC provider; NorQuest College also offers online and hybrid options." },
      { id: 'library', text: 'Free Edmonton Public Library card: access computers, printing, language learning resources, and community programs. No cost, requires only proof of address.' },
      { id: 'events', text: 'Newcomer Centre monthly events: peer support, employment info sessions, cultural groups.' },
      { id: 'programs', text: 'Newcomer Centre programs: I-WIN (immigrant women\'s network), Youth Leading Change (YLC), Global Girls.' },
      { id: 'volunteer', text: 'Volunteer: volunteering builds Canadian references and social connections. Libraries, food banks, and cultural organizations welcome newcomers.' },
    ],
    documents: [
      { id: 'status', name: 'Proof of immigration status', whyNeeded: 'Required for LINC eligibility', whereToGet: 'Your immigration document or PR card' },
    ],
    resources: [
      { label: 'EMCN LINC registration', url: 'https://emcn.ab.ca/linc' },
      { label: 'NorQuest LINC', url: 'https://www.norquest.ca/programs-courses/english-language/linc.aspx' },
      { label: 'Edmonton Public Library — new card', url: 'https://www.epl.ca/get-a-library-card' },
    ],
    personaNotes: [
      { status: 'refugee', note: 'Refugees get priority LINC enrollment. Arabic-language cohorts are available at EMCN.' },
    ],
  },
  {
    id: 'step_7_taxes',
    stepNumber: 7,
    title: 'Tax filing & federal benefits',
    timing: 'Month 2–3',
    offlineAvailable: false,
    whyItMatters: 'Filing a tax return — even with zero income — activates GST/HST credit, Canada Child Benefit, and other income-based programs. Do not skip this.',
    actions: [
      { id: 'file', text: 'File your first T1 return even if you had no income in Canada. Use TurboTax, Wealthsimple Tax (free for simple returns), or attend a free community tax clinic.' },
      { id: 'ccb', text: 'Canada Child Benefit (CCB): up to $7,437/yr per child under 6, $6,275 for ages 6–17. Apply separately at CRA — do not wait for your tax return.' },
      { id: 'gst', text: 'GST/HST credit: quarterly payments for low/moderate income residents. Activated automatically by filing taxes.' },
      { id: 'cdcp', text: 'Canadian Dental Care Plan (CDCP): federal dental coverage if no private insurance and household income under $90,000.' },
      { id: 'provincial', text: 'Alberta Seniors Benefit, AISH (disability), FSCD (children with disabilities) — check the eligibility screener in-app.' },
    ],
    documents: [
      { id: 'sin', name: 'SIN', whyNeeded: 'Required for all CRA filings', whereToGet: 'Service Canada (applied in Step 1)' },
      { id: 't4', name: 'T4 slips from employer', whyNeeded: 'Income reporting', whereToGet: 'From your employer by end of February' },
      { id: 'dates', name: 'All immigration dates (entry/exit)', whyNeeded: 'Residency calculation for tax purposes', whereToGet: 'Passport stamps and IRCC records' },
    ],
    resources: [
      { label: 'Wealthsimple Tax — free filing', url: 'https://www.wealthsimple.com/en-ca/tax' },
      { label: 'Canada Child Benefit — apply at CRA', url: 'https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview.html' },
      { label: 'Canadian Dental Care Plan (CDCP)', url: 'https://www.canada.ca/en/services/benefits/dental/dental-care-plan.html' },
    ],
    personaNotes: [
      { status: 'pr', note: 'Tax filing as a PR has different rules than as a student or temporary resident — clarify your residency status at CRA.' },
      { status: 'study_permit', note: 'You may still be eligible for GST credit and CCB as a study permit holder depending on residency.' },
    ],
  },
  {
    id: 'step_8_licence',
    stepNumber: 8,
    title: "Driver's licence & transportation",
    timing: 'Month 3',
    offlineAvailable: true,
    whyItMatters: "Alberta accepts many foreign driver's licences for direct exchange — but the process has country-specific rules and a 90-day window.",
    actions: [
      { id: 'check', text: 'Check your country: about 40 countries qualify for direct licence exchange with no road test. Others require a written or road test. See the lookup table below.' },
      { id: 'exchange', text: "Exchange at Alberta Registry: bring foreign licence + passport + proof of Alberta address + applicable fee (~$30)." },
      { id: 'gdl', text: 'If no qualifying licence: graduated licensing (GDL) — written knowledge test → 12 months with Class 7 → road test for Class 5.' },
      { id: 'transit', text: 'ETS (Edmonton Transit Service) Arc card: $100/month unlimited pass. Seniors 65+ and youth 6–17 have lower monthly caps. Load online or at Shoppers Drug Mart.' },
      { id: 'winter', text: 'Winter driving: block heater use is standard (plug in at -15°C or below), snow tires recommended, warm-up car before driving in deep freeze.' },
    ],
    documents: [
      { id: 'licence', name: "Foreign driver's licence", whyNeeded: 'Required for exchange', whereToGet: 'You already have this' },
      { id: 'passport', name: 'Passport', whyNeeded: 'Identity verification', whereToGet: 'You already have this' },
      { id: 'address', name: 'Proof of Alberta address', whyNeeded: 'Residency confirmation', whereToGet: 'Lease or utility bill' },
    ],
    resources: [
      { label: 'Alberta Registry — licence exchange', url: 'https://www.alberta.ca/exchange-your-out-of-province-licence.aspx' },
      { label: 'ETS Arc card — Edmonton Transit', url: 'https://www.edmonton.ca/transit/arc' },
    ],
    personaNotes: [
      { status: 'pr', note: 'Philippines, Ukraine, Sudan (some regions), and India are among the 40+ countries with direct exchange. Check the registry for your country.' },
      { status: 'cuaet', note: 'Ukraine qualifies for direct licence exchange — no road test required.' },
      { status: 'work_permit', note: 'Philippines qualifies for direct exchange. Bring your original Philippine LTO licence.' },
    ],
  },
  {
    id: 'step_9_citizenship',
    stepNumber: 9,
    title: 'Citizenship pathway',
    timing: 'Month 3+',
    offlineAvailable: false,
    whyItMatters: 'Understanding the path from PR to citizenship helps newcomers plan for the long term and track their eligibility clock from day one.',
    actions: [
      { id: 'eligibility', text: 'Eligibility: 3 of the last 5 years physically present in Canada as a PR. The app tracks your days automatically once you enter your PR date.' },
      { id: 'language', text: 'Language requirement: Canadian Language Benchmark (CLB) 4 in English or French. Free test prep resources are linked in the resources section.' },
      { id: 'test', text: "Knowledge test: based on 'Discover Canada' guide — 20 questions, must score 15+. Free study materials at EMCN and Edmonton Public Library." },
      { id: 'apply', text: 'Application: online via IRCC portal. Current processing time is approximately 12–18 months.' },
      { id: 'absences', text: 'Prohibited absences: certain travel can affect day counts — trips over 182 days in a single period are flagged.' },
      { id: 'dual', text: "Dual citizenship: Canada allows dual citizenship — check your home country's rules before applying." },
    ],
    documents: [
      { id: 'pr', name: 'PR card with issue date', whyNeeded: 'Proves PR status and start of eligibility clock', whereToGet: 'Issued by IRCC when PR approved' },
      { id: 'travel', name: 'Travel history', whyNeeded: 'Physical presence calculation', whereToGet: 'Passport stamps and IRCC travel history' },
    ],
    resources: [
      { label: 'Apply for citizenship — IRCC', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/canadian-citizenship/become-candidate.html' },
      { label: 'Discover Canada guide', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/corporate/publications-manuals/discover-canada.html' },
      { label: 'EMCN citizenship prep classes', url: 'https://emcn.ab.ca/programs/citizenship' },
    ],
    personaNotes: [
      { status: 'pr', note: 'Track your physical presence days from your PR approval date — every day counts toward the 3-of-5 requirement.' },
      { status: 'study_permit', note: 'Days on a study permit before PR count as half days toward citizenship — up to 365 days credit.' },
    ],
  },
];
